﻿title: 丁鞠桐的学术主页 | Jutong Ding's Academic Homepage
page-top-title: 丁鞠桐 | Jutong Ding
top-section-bg-text: 人形机器人 | Humanoid Robotics
home-subtitle: 人形机器人与灵巧手&ensp;|&ensp;Humanoid Robots & Dexterous Hands
copyright-text: '&copy; 丁鞠桐 2026. 版权所有 | All Rights Reserved.'